export const CONTACT_INFO = {
  brandName: 'S&I Atelier',
  brandFullName: 'S&I Atelier',
  whatsappNumber: '+966 50 123 4567',
  whatsappRaw: '966501234567',
  phone: '+966 50 123 4567',
  vipLine: '+966 11 456 7890',
  email: 'concierge@atelier-luxury.com',
  address: 'طريق الملك فهد، حي العليا، الرياض، المملكة العربية السعودية',
  googleMapsUrl: 'https://maps.google.com/?q=Riyadh+Olaya+King+Fahd+Road',
  instagramUrl: 'https://instagram.com/atelier_luxury',
  snapchatUrl: 'https://snapchat.com/add/atelier_luxury',
  tiktokUrl: 'https://tiktok.com/@atelier_luxury',
  twitterUrl: 'https://x.com/atelier_luxury',
  pinterestUrl: 'https://pinterest.com/atelier_luxury',
  linkedinUrl: 'https://linkedin.com/company/atelier-luxury',
  facebookUrl: 'https://facebook.com/atelierluxury',
  youtubeUrl: 'https://youtube.com/@atelier_luxury',
  workingHours: 'السبت - الخميس: 10:00 ص - 10:00 م | الجمعة: 4:00 م - 10:00 م'
}
